### ISSUE TITLE
Week 2 Presentations Review Ticket

### ISSUE THREAD

**Issue by jeankim05** [jeankim05/tri3teambigmac#27]
- [x] Big Idea, Sponsor, Hosting Plan, Github License
- [x] WireFrames or Web Page mock ups
- [x] Key Workflow or Actions
- [x] Data and any Data Privacy or Security needed.  For instance between Admin and Users of system.
[Link to presentation on wiki as evidence](https://github.com/jeankim05/tri3teambigmac/wiki/Week-2-Presentation-DN-PPOO)

**Comment by peacekeeper6** [comment]
Suggestions/Feedback:

- Club about page (?)
- Admin access vs user access
- Announcements go out as emails
