### ISSUE TITLE
Notes and Members Database

### ISSUE THREAD

**Issue by jeankim05** [jeankim05/tri3teambigmac#43]

**Comment by aidanywu** [comment]
[Commit](https://github.com/jeankim05/tri3teambigmac/commit/b0558165278518dd50fa80c2e35e4f2d18bd5112)
[new model.py](https://github.com/jeankim05/tri3teambigmac/blob/Aidan/timelinecrud/model.py)
[new app_timeline.py](https://github.com/jeankim05/tri3teambigmac/blob/Aidan/timelinecrud/app_timeline.py)
[new timeline.html](https://github.com/jeankim05/tri3teambigmac/blob/Aidan/timelinecrud/templates/timeline/timeline.html)
