### ISSUE TITLE
Week 9 Review Ticket: Aidan Wu

### ISSUE THREAD

**Issue by jeankim05** [jeankim05/tri3teambigmac#53]
Assigned Tasks for the Week

1. Incorporate administration
    - [Ticket](https://github.com/jeankim05/tri3teambigmac/issues/11)
2. New table in database, timeline
    - [Ticket](https://github.com/jeankim05/tri3teambigmac/issues/43)
3. Timestamps for the new table
    - [Ticket](https://github.com/jeankim05/tri3teambigmac/issues/57)

**Comment by peacekeeper6** [comment]
Grade: 1.8/2

Aidan incorporated administration and privilege levels in order to allow records to be adjusted and viewed by only certain accounts. A new table was added for timelines, and timestamps (notes) for the table
