### ISSUE TITLE
Week 9 Review Ticket: Jun Lim

### ISSUE THREAD

**Issue by jeankim05** [jeankim05/tri3teambigmac#54]
1. [Events Calendar](https://github.com/jeankim05/tri3teambigmac/commit/58d9736a2d8bd0fb4d5d666368fef379e518653c) Note: Connor took over the Events Calendar after I started, and I took over the Get Involved Page after he started.
3. [Get Involved Page](https://github.com/jeankim05/tri3teambigmac/commit/b0f73ccb3caa5b479041f069ab188ce4df1258c3)
4. Deployment - dnprojectpoo.cf + [Deployment Changes Wiki](https://github.com/jeankim05/tri3teambigmac/wiki/Deployment-Changes)

**Comment by aidanywu** [comment]
Grade: 1.8

Created a lot of CSS for the calendar which makes the page look a lot nicer and have good animation. Also coded the Javascript that makes the calendar work.
